package:
  name: dqmarc
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools_scm
    - setuptools_scm_git_archive
    - python {{ python }}
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pandas
    - numpy
    - ipydatagrid
    - ipywidgets
    - plotly
    - shiny
    - shinywidgets
    - jupyterlab

about:
  home: https://github.com/christie-nhs-data-science/DQMaRC
  license: MIT License and Open Government License v3
  summary: DQMaRC is a python tool for data quality profiling of structured tabular data.
  documentation: https://christie-nhs-data-science.github.io/DQMaRC/
