name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/DQMaRC

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs: publish-to-testpypi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/DQMaRC

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        user: __token__
        password: ${{ secrets.pypi_password }}
        repository-url: https://upload.pypi.org/legacy/

  publish-to-conda:
    name: Publish to Conda
    needs: publish-to-pypi
    runs-on: ubuntu-latest

    steps:
      - name: Install conda-build and anaconda-client
        shell: bash -l {0}  # Load the shell with Conda initialized
        run: |
          conda install -y conda-build anaconda-client
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate base
          anaconda login --username "${{ secrets.conda_username }}" --password "${{ secrets.conda_password }}"

      - name: Build Conda package
        run: conda build ./DQMaRC/conda_recipe

      - name: Upload to Conda
        run: |
          anaconda upload ./dist/dqmarc-1.0.2-*.tar.bz2 --user "${{ secrets.conda_username }}"
