name: Build and Deploy Sphinx Documentation

# credit to: https://redandgreen.co.uk/sphinx-to-github-pages-via-github-actions/

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_docs_job: # name of this job
    runs-on: ubuntu-latest # virtual machine name to run github actions
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # step 1: Checkout repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # step 2: Set up Python and install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version

      # (optional) Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # step 3: Set up Python and install dependencies
      - name: Install dependencies
        run: | # pipe for multiple action lines
          python -m pip install --upgrade pip
          pip install -r docs/docs_requirements.txt  # file in docs/... folder

      # step 4: build docs
      - name: build sphinx HTML docs
        run: |
          ./docs/make clean html
          ./docs/make html

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/build/html
  
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
